# Generated by Django 4.2.3 on 2023-08-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulopedido',
            name='imagen',
            field=models.CharField(default='', max_length=500),
        ),
    ]
