# Generated by Django 4.2.3 on 2023-08-04 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_valoraciones_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='producto.producto'),
        ),
    ]
